spring.application.name=wealthengine

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wealthengine}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:wealthengine}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:wealthengine123}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration